FROM dockerfile/java

#RUN wget http://www.carfab.com/apachesoftware/cassandra/2.0.6/apache-cassandra-2.0.6-bin.tar.gz
RUN wget http://www.apache.org/dyn/closer.cgi?path=/cassandra/2.0.7/apache-cassandra-2.0.7-bin.tar.gz
